//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Cliente.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WSCuilSoap")]
    public interface WSCuilSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ValidarCuilResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarCuil", ReplyAction="*")]
        UI.Cliente.ServiceReference.ValidarCuilResponse ValidarCuil(UI.Cliente.ServiceReference.ValidarCuilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarCuil", ReplyAction="*")]
        System.Threading.Tasks.Task<UI.Cliente.ServiceReference.ValidarCuilResponse> ValidarCuilAsync(UI.Cliente.ServiceReference.ValidarCuilRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCuilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCuil", Namespace="http://tempuri.org/", Order=0)]
        public UI.Cliente.ServiceReference.ValidarCuilRequestBody Body;
        
        public ValidarCuilRequest() {
        }
        
        public ValidarCuilRequest(UI.Cliente.ServiceReference.ValidarCuilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarCuilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DNI;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DigitoVerificador;
        
        public ValidarCuilRequestBody() {
        }
        
        public ValidarCuilRequestBody(int Tipo, int DNI, int DigitoVerificador) {
            this.Tipo = Tipo;
            this.DNI = DNI;
            this.DigitoVerificador = DigitoVerificador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarCuilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCuilResponse", Namespace="http://tempuri.org/", Order=0)]
        public UI.Cliente.ServiceReference.ValidarCuilResponseBody Body;
        
        public ValidarCuilResponse() {
        }
        
        public ValidarCuilResponse(UI.Cliente.ServiceReference.ValidarCuilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarCuilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarCuilResult;
        
        public ValidarCuilResponseBody() {
        }
        
        public ValidarCuilResponseBody(string ValidarCuilResult) {
            this.ValidarCuilResult = ValidarCuilResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCuilSoapChannel : UI.Cliente.ServiceReference.WSCuilSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCuilSoapClient : System.ServiceModel.ClientBase<UI.Cliente.ServiceReference.WSCuilSoap>, UI.Cliente.ServiceReference.WSCuilSoap {
        
        public WSCuilSoapClient() {
        }
        
        public WSCuilSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCuilSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCuilSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCuilSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UI.Cliente.ServiceReference.ValidarCuilResponse UI.Cliente.ServiceReference.WSCuilSoap.ValidarCuil(UI.Cliente.ServiceReference.ValidarCuilRequest request) {
            return base.Channel.ValidarCuil(request);
        }
        
        public string ValidarCuil(int Tipo, int DNI, int DigitoVerificador) {
            UI.Cliente.ServiceReference.ValidarCuilRequest inValue = new UI.Cliente.ServiceReference.ValidarCuilRequest();
            inValue.Body = new UI.Cliente.ServiceReference.ValidarCuilRequestBody();
            inValue.Body.Tipo = Tipo;
            inValue.Body.DNI = DNI;
            inValue.Body.DigitoVerificador = DigitoVerificador;
            UI.Cliente.ServiceReference.ValidarCuilResponse retVal = ((UI.Cliente.ServiceReference.WSCuilSoap)(this)).ValidarCuil(inValue);
            return retVal.Body.ValidarCuilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UI.Cliente.ServiceReference.ValidarCuilResponse> UI.Cliente.ServiceReference.WSCuilSoap.ValidarCuilAsync(UI.Cliente.ServiceReference.ValidarCuilRequest request) {
            return base.Channel.ValidarCuilAsync(request);
        }
        
        public System.Threading.Tasks.Task<UI.Cliente.ServiceReference.ValidarCuilResponse> ValidarCuilAsync(int Tipo, int DNI, int DigitoVerificador) {
            UI.Cliente.ServiceReference.ValidarCuilRequest inValue = new UI.Cliente.ServiceReference.ValidarCuilRequest();
            inValue.Body = new UI.Cliente.ServiceReference.ValidarCuilRequestBody();
            inValue.Body.Tipo = Tipo;
            inValue.Body.DNI = DNI;
            inValue.Body.DigitoVerificador = DigitoVerificador;
            return ((UI.Cliente.ServiceReference.WSCuilSoap)(this)).ValidarCuilAsync(inValue);
        }
    }
}
